// Copyright (c) 2023 IndyKite
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/neo4j/neo4j-go-driver/v6/neo4j (interfaces: ManagedTransaction,Result)
//
// Generated by this command:
//
//	mockgen -copyright_file ../doc/LICENSE -package test -destination ./neo4j_mock.go github.com/neo4j/neo4j-go-driver/v6/neo4j ManagedTransaction,Result
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	neo4j "github.com/neo4j/neo4j-go-driver/v6/neo4j"
	gomock "go.uber.org/mock/gomock"
)

// MockManagedTransaction is a mock of ManagedTransaction interface.
type MockManagedTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockManagedTransactionMockRecorder
	isgomock struct{}
}

// MockManagedTransactionMockRecorder is the mock recorder for MockManagedTransaction.
type MockManagedTransactionMockRecorder struct {
	mock *MockManagedTransaction
}

// NewMockManagedTransaction creates a new mock instance.
func NewMockManagedTransaction(ctrl *gomock.Controller) *MockManagedTransaction {
	mock := &MockManagedTransaction{ctrl: ctrl}
	mock.recorder = &MockManagedTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagedTransaction) EXPECT() *MockManagedTransactionMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockManagedTransaction) Run(ctx context.Context, cypher string, params map[string]any) (neo4j.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, cypher, params)
	ret0, _ := ret[0].(neo4j.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockManagedTransactionMockRecorder) Run(ctx, cypher, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockManagedTransaction)(nil).Run), ctx, cypher, params)
}

// MockResult is a mock of Result interface.
type MockResult struct {
	neo4j.Result
	ctrl     *gomock.Controller
	recorder *MockResultMockRecorder
	isgomock struct{}
}

// MockResultMockRecorder is the mock recorder for MockResult.
type MockResultMockRecorder struct {
	mock *MockResult
}

// NewMockResult creates a new mock instance.
func NewMockResult(ctrl *gomock.Controller) *MockResult {
	mock := &MockResult{ctrl: ctrl}
	mock.recorder = &MockResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResult) EXPECT() *MockResultMockRecorder {
	return m.recorder
}

// Collect mocks base method.
func (m *MockResult) Collect(ctx context.Context) ([]*neo4j.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect", ctx)
	ret0, _ := ret[0].([]*neo4j.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Collect indicates an expected call of Collect.
func (mr *MockResultMockRecorder) Collect(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockResult)(nil).Collect), ctx)
}

// Consume mocks base method.
func (m *MockResult) Consume(ctx context.Context) (neo4j.ResultSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx)
	ret0, _ := ret[0].(neo4j.ResultSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockResultMockRecorder) Consume(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockResult)(nil).Consume), ctx)
}

// Err mocks base method.
func (m *MockResult) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockResultMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockResult)(nil).Err))
}

// IsOpen mocks base method.
func (m *MockResult) IsOpen() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOpen")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsOpen indicates an expected call of IsOpen.
func (mr *MockResultMockRecorder) IsOpen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOpen", reflect.TypeOf((*MockResult)(nil).IsOpen))
}

// Keys mocks base method.
func (m *MockResult) Keys() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Keys indicates an expected call of Keys.
func (mr *MockResultMockRecorder) Keys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockResult)(nil).Keys))
}

// Next mocks base method.
func (m *MockResult) Next(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockResultMockRecorder) Next(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockResult)(nil).Next), ctx)
}

// NextRecord mocks base method.
func (m *MockResult) NextRecord(ctx context.Context, record **neo4j.Record) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextRecord", ctx, record)
	ret0, _ := ret[0].(bool)
	return ret0
}

// NextRecord indicates an expected call of NextRecord.
func (mr *MockResultMockRecorder) NextRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextRecord", reflect.TypeOf((*MockResult)(nil).NextRecord), ctx, record)
}

// Peek mocks base method.
func (m *MockResult) Peek(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peek", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Peek indicates an expected call of Peek.
func (mr *MockResultMockRecorder) Peek(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peek", reflect.TypeOf((*MockResult)(nil).Peek), ctx)
}

// PeekRecord mocks base method.
func (m *MockResult) PeekRecord(ctx context.Context, record **neo4j.Record) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PeekRecord", ctx, record)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PeekRecord indicates an expected call of PeekRecord.
func (mr *MockResultMockRecorder) PeekRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PeekRecord", reflect.TypeOf((*MockResult)(nil).PeekRecord), ctx, record)
}

// Record mocks base method.
func (m *MockResult) Record() *neo4j.Record {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record")
	ret0, _ := ret[0].(*neo4j.Record)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockResultMockRecorder) Record() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockResult)(nil).Record))
}

// Records mocks base method.
func (m *MockResult) Records(ctx context.Context) func(func(*neo4j.Record, error) bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Records", ctx)
	ret0, _ := ret[0].(func(func(*neo4j.Record, error) bool))
	return ret0
}

// Records indicates an expected call of Records.
func (mr *MockResultMockRecorder) Records(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Records", reflect.TypeOf((*MockResult)(nil).Records), ctx)
}

// Single mocks base method.
func (m *MockResult) Single(ctx context.Context) (*neo4j.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Single", ctx)
	ret0, _ := ret[0].(*neo4j.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Single indicates an expected call of Single.
func (mr *MockResultMockRecorder) Single(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Single", reflect.TypeOf((*MockResult)(nil).Single), ctx)
}

// buffer mocks base method.
func (m *MockResult) buffer(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "buffer", ctx)
}

// buffer indicates an expected call of buffer.
func (mr *MockResultMockRecorder) buffer(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "buffer", reflect.TypeOf((*MockResult)(nil).buffer), ctx)
}

// errorHandler mocks base method.
func (m *MockResult) errorHandler(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "errorHandler", err)
}

// errorHandler indicates an expected call of errorHandler.
func (mr *MockResultMockRecorder) errorHandler(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "errorHandler", reflect.TypeOf((*MockResult)(nil).errorHandler), err)
}
