---
linters:
    enable:
        # By Default
        - deadcode
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unused
        - varcheck

        # Extra
        - lll
        - asciicheck
        - cyclop
        - gocritic
        - revive
        - gosec
        - gofmt
        - goimports
        - ifshort
        - prealloc
        - unconvert
        - whitespace

linters-settings:
    govet:
        check-shadowing: true
    lll:
        line-length: 120
        tab-width: 4
    goimports:
        local-prefixes: github.com/indykite/neo4j-graph-tool-core
    staticcheck:
        go: '1.17'
        checks: [all, -ST1000]
    stylecheck:
        go: '1.17'
        checks: [all, -ST1000]
issues:
    exclude-use-default: false # Some rules are excluded by GolangCI Linter by default, this one will prevent that
    max-issues-per-linter: 0
    max-same-issues: 0

    exclude-rules:
        - linters:
              - revive
          text: exported .* should have comment .*or be unexported
