---
name: Lint and test
on: [push]

concurrency:
    group: pr-${{ github.ref }}
    cancel-in-progress: true

jobs:
    golangci:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codebase
              uses: indykite/.github/.github/actions/git-checkout@master # actions/checkout with dynamic fetch-depth resolution

            - name: Set up Go
              uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0 - https://github.com/actions/setup-go/releases
              with:
                  go-version-file: go.mod

            - name: Run GolangCI-Lint Scanner
              uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0 - https://github.com/golangci/golangci-lint-action/releases
              with:
                  version: v2.13.2 # renovate: datasource=github-releases,depName=golangci/golangci-lint

    test:
        name: Test and coverage
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: indykite/.github/.github/actions/git-checkout@master # actions/checkout with dynamic fetch-depth resolution

            - name: Set up Go
              uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0 - https://github.com/actions/setup-go/releases
              with:
                  go-version-file: go.mod

            - name: Run Unit tests.
              run: make test

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0 - https://github.com/codecov/codecov-action/releases
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage.out
                  # Notify us when failed, so devs are not waiting for Codecov report when it will never come.
                  # Because Codecov report is required to be able to merge, we have to run again the whole test anyway.
                  fail_ci_if_error: true
